#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
import sys
from .ttypes import *
OPTION_PREFER_SHORTEST = 1
OPTION_PREFER_SAFER = 2
OPTION_PREFER_HIGHSEC = 4
