<?php
namespace cynoup\routing;

/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


final class Constant extends \Thrift\Type\TConstant {
  static protected $OPTION_PREFER_SHORTEST;
  static protected $OPTION_PREFER_SAFER;
  static protected $OPTION_PREFER_HIGHSEC;

  static protected function init_OPTION_PREFER_SHORTEST() {
    return 1;
  }

  static protected function init_OPTION_PREFER_SAFER() {
    return 2;
  }

  static protected function init_OPTION_PREFER_HIGHSEC() {
    return 4;
  }
}


